# Generated by Django 5.0.3 on 2024-03-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Diaries",
        ),
    ]
