# Generated by Django 5.0.3 on 2024-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diaries",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("memo", models.TextField()),
                ("tags", models.TextField()),
            ],
            options={
                "db_table": "Diaries",
                "managed": False,
            },
        ),
    ]
